set wshshell = wscript.CreateObject("WScript.shell")
do
wshshell.sendkeys "{CAPSLOCK}"
wshshell.sendkeys "{NUMLOCK}"
wshshell.sendkeys "{SCROLLLOCK}"
wshshell.sendkeys "Q"
wshshell.sendkeys "W"
wshshell.sendkeys "E"
wshshell.sendkeys "R"
wshshell.sendkeys "T"
wshshell.sendkeys "Y"
wshshell.sendkeys "A"
wshshell.sendkeys "S"
wshshell.sendkeys "D"
wshshell.sendkeys "F"
wshshell.sendkeys "G"
wshshell.sendkeys "H"
wshshell.sendkeys "J"
wshshell.sendkeys "K"
wshshell.sendkeys "L"
wshshell.sendkeys "Z"
wshshell.sendkeys "X"
wshshell.sendkeys "C"
wshshell.sendkeys "V"
wshshell.sendkeys "B"
wshshell.sendkeys "N"
wshshell.sendkeys "M"
loop

